bibtex_bibfiles:
- ../paper.bib
execute:
  timeout: 600
launch_buttons:
  binderhub_url: https://binder-mcgill.conp.cloud
  notebook_interface: jupyterlab
logo: logo.png
only_build_toc_files: true
repository:
  branch: main
  path_to_book: content
  url: https://github.com/roboneurolibre/note
sphinx:
  config:
    bibtex_default_style: plain
    bibtex_reference_style: author_year
    bibtex_tooltips: true
    html_css_files:
    - custom.css
    html_static_path:
    - _static
  local_extensions: null
  recursive_update: false
title: 2020 T1 Reproducibility Challenge
